2018 acura tlx
sunnypilot/sunnypilot pull request #342
Opened 2024-06-04 12:42 UTC by mlocoteta

Adding TLX , verified on regular 9th gen accord and 2018 TLX. Not sure the years supported at this time. 

There was some bug fixes required in carstate.py. Specifically it looks like many models were renamed from something like CAR.CIVIC to CAR.HONDA_CIVIC. The only one which I wasn't quite sure about was CAR.ACCORDH - I couldn't find a replacement for this one. Everything else seemed pretty straight forward, some of the spacing changes are due to the checks before commit (unused variables/ line length > 160 characters). 

Todo: 
Need to generate docs.py.

- [\] added entry to CAR in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [X] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [X] route with openpilot: dc27c011224d353f/00000023--d15078f2fd/0
- [X] route with stock system: dc27c011224d353f/00000027--e5009d2033/0
- [X] car harness used (if comma doesn't sell it, put N/A): N/A - Serial Steering V3 board

2024-06-04 14:36 UTC, mlocoteta commented
There's a problem with the car docs- it looks like 2022 Hyundai Elantra is missing params, However, the TLX should have necessary params

2024-06-19 04:05 UTC, mlocoteta commented
Rebased to latest, fixed .gitmodules and what submodules point to.

2024-08-02 02:48 UTC, sunnyhaibin commented
@mlocoteta Can you please point this PR against `master`? Thanks!

2024-08-02 02:50 UTC, sunnyhaibin requested changes

2024-08-02 02:50 UTC, sunnyhaibin commented on selfdrive/car/honda/interface.py
> -      tire_stiffness_factor = 0.8467
Let's remove this in a separate PR.

2024-08-02 02:50 UTC, sunnyhaibin commented on selfdrive/car/honda/interface.py
> -      tire_stiffness_factor = 1.
Same as the above.

2024-09-28 00:47 UTC, sidbmw commented
Which engine is this for and FWD or SH-AWD? Not sure if those make a difference. Might be worth adding trim info.

2025-03-14 23:21 UTC, sunnyhaibin commented
Can you reopen this PR against the `master-new` branch at https://github.com/sunnypilot/opendbc?

2025-03-14 23:21 UTC, closed without merging